export const ACTORS = [
    { 
      id: 1, 
      name: 'Melissa', 
      thumbnail: '👩🏻',
      imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Melissa.png',
      category: 'Female', 
    },
    { id: 2, name: 'David', thumbnail: '👨🏽', category: 'Male' , imageUrl : "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/David.png" },

    {
    id: 3,
    name: "Alex",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Alex_Caucasian_Young_Male.png",
  },
  {
    id: 4,
    name: "Anna",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Anna_Caucasian_Young_Female.png",
  },
  {
    id: 5,
    name: "Darius",
    thumbnail: "👨🏾",
    category: "Male",
    Age: "Young",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Darius_Black_Young_Male.png",
  },
  {
    id: 6,
    name: "David",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/David_Caucasian_Young_Male.png",
  },
  {
    id: 7,
    name: "Emily",
    thumbnail: "👩🏻",
    category: "Female",
    Age: "Old",
    Race: "Asian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Emily_Asian_Old_Female.png",
  },
  {
    id: 8,
    name: "Hannah",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Hannah_Caucasian_Young_Female.png",
  },
  {
    id: 9,
    name: "Jake",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Jake_Caucasian_Young_Male.png",
  },
  {
    id: 10,
    name: "Jasmine",
    thumbnail: "👩🏾",
    category: "Female",
    Age: "Young",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Jasmine_Black_Young_Female.png",
  },
  {
    id: 11,
    name: "Jessica",
    thumbnail: "👩🏻",
    category: "Female",
    Age: "Young",
    Race: "Asian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Jessica_Asian_Young_Female.png",
  },
  {
    id: 12,
    name: "John",
    thumbnail: "👨🏾",
    category: "Male",
    Age: "Old",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/John_Black_Old_Male.png",
  },
  {
    id: 13,
    name: "John",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/John_Caucasian_Old_Male.png",
  },
  {
    id: 14,
    name: "Kayla",
    thumbnail: "👩🏾",
    category: "Female",
    Age: "Old",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Kayla_Black_Old_Female.png",
  },
  {
    id: 15,
    name: "Linda",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Linda_Caucasian_Old_Female.png",
  },
  {
    id: 17,
    name: "Madison",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Madison_Caucasian_Young_Female.png",
  },
  {
    id: 18,
    name: "Michael",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Michael_Caucasian_Old_Male.png",
  },
  {
    id: 19,
    name: "Natalie",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Natalie_Caucasian_Young_Female.png",
  },
  {
    id: 20,
    name: "Ryan",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Ryan_Caucasian_Young_Male.png",
  },
  {
    id: 21,
    name: "Susan",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Susan_Caucasian_Old_Female.png",
  },
  {
    id: 22,
    name: "Tyler",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Tyler_Caucasian_Young_Male.png",
  }  ,
  {
    id: 24,
    name: 'Audrey',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Audrey_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 25,
    name: 'Chloe',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Chloe_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 26,
    name: 'Hannah',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Hannah_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 27,
    name: 'Ruby',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Ruby_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 29,
    name: 'Willow',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Willow_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 30,
    name: 'Hadley',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Hadley_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 31,
    name: 'Bella',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Bella_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 32,
    name: 'Sophie',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Sophie_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 33,
    name: 'Layla',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Layla_Caucasian_Young_Female.png',
    category: 'Female',
  },
  {
    id: 34,
    name: 'Ivy',
    thumbnail: '👩🏻',
    imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Ivy_Caucasian_Young_Female.png',
    category: 'Female',
  },
  ]
  
const KIE_PREVIEW_BASE = 'https://static.aiquickdraw.com/elevenlabs/voice'

const KIE_VOICES = [
  { id: 'EkK5I93UQWFDigLMpZcX', name: 'James',                    description: 'Husky, Engaging and Bold',            gender: 'Male'   },
  { id: 'Z3R5wn05IrDiVCyEkUrK', name: 'Arabella',                 description: 'Mysterious and Emotive',             gender: 'Female' },
  { id: 'NNl6r8mD7vthiJatiJt1', name: 'Bradford',                 description: 'Expressive and Articulate',          gender: 'Male'   },
  { id: 'B8gJV1IhpuegLxdpXFOE', name: 'Kuon',                     description: 'Cheerful, Clear and Steady',         gender: 'Male'   },
  { id: '2zRM7PkgwBPiau2jvVXc', name: 'Monika Sogam',             description: 'Deep and Natural',                   gender: 'Female' },
  { id: '1SM7GgM6IMuvQlz2BwM3', name: 'Mark',                     description: 'Casual, Relaxed and Light',          gender: 'Male'   },
  { id: '5l5f8iK3YPeGga21rQIX', name: 'Adeline',                  description: 'Feminine and Conversational',        gender: 'Female' },
  { id: 'scOwDtmlUjD3prqpp97I', name: 'Sam',                      description: 'Support Agent',                      gender: 'Male'   },
  { id: 'NOpBlnGInO9m6vDvFkFC', name: 'Spuds Oxley',              description: 'Wise and Approachable',              gender: 'Male'   },
  { id: 'BZgkqPqms7Kj9ulSkVzn', name: 'Eve',                      description: 'Authentic, Energetic and Happy',     gender: 'Female' },
  { id: 'wo6udizrrtpIxWGp2qJk', name: 'Northern Terry',           description: 'Northern accent',                    gender: 'Male'   },
  { id: 'gU0LNdkMOQCOrPrwtbee', name: 'British Football Announcer', description: 'Bold and Loud',                   gender: 'Male'   },
  { id: 'DGzg6RaUqxGRTHSBjfgF', name: 'Brock',                    description: 'Commanding and Loud Sergeant',       gender: 'Male'   },
  { id: 'x70vRnQBMBu4FAYhjJbO', name: 'Nathan',                   description: 'Virtual Radio Host',                 gender: 'Male'   },
  { id: 'Sm1seazb4gs7RSlUVw7c', name: 'Anika',                    description: 'Animated, Friendly and Engaging',    gender: 'Female' },
  { id: 'P1bg08DkjqiVEzOn76yG', name: 'Viraj',                    description: 'Rich and Soft',                      gender: 'Male'   },
  { id: 'qDuRKMlYmrm8trt5QyBn', name: 'Taksh',                    description: 'Calm, Serious and Smooth',           gender: 'Male'   },
  { id: 'TX3LPaxmHKxFdv7VOQHJ', name: 'Liam',                     description: 'Energetic, Social Media Creator',    gender: 'Male'   },
  { id: 'N2lVS1w4EtoT3dr4eOWO', name: 'Callum',                   description: 'Husky Trickster',                    gender: 'Male'   },
  { id: 'FGY2WhTYpPnrIDTdsKH5', name: 'Laura',                    description: 'Enthusiast, Quirky Attitude',        gender: 'Female' },
  { id: 'kPzsL2i3teMYv0FxEYQ6', name: 'Brittney',                 description: 'Fun, Youthful & Informative',        gender: 'Female' },
  { id: 'UgBBYS2sOqTuMpoF3BR0', name: 'Mark (Natural)',           description: 'Natural Conversations',              gender: 'Male'   },
  { id: 'hpp4J3VqNfWAUOO0d1Us', name: 'Bella',                    description: 'Professional, Bright, Warm',         gender: 'Female' },
  { id: 'nPczCjzI2devNBz1zQrb', name: 'Brian',                    description: 'Deep, Resonant and Comforting',      gender: 'Male'   },
  { id: 'uYXf8XasLslADfZ2MB4u', name: 'Hope',                     description: 'Bubbly, Gossipy and Girly',          gender: 'Female' },
  { id: 'gs0tAILXbY5DNrJrsM6F', name: 'Jeff',                     description: 'Classy, Resonating and Strong',      gender: 'Male'   },
  { id: 'DTKMou8ccj1ZaWGBiotd', name: 'Jamahal',                  description: 'Young, Vibrant, and Natural',        gender: 'Male'   },
  { id: 'vBKc2FfBKJfcZNyEt1n6', name: 'Finn',                     description: 'Youthful, Eager and Energetic',      gender: 'Male'   },
  { id: 'DYkrAHD8iwork3YSUBbs', name: 'Tom',                      description: 'Conversations & Books',              gender: 'Male'   },
  { id: '56AoDkrOh6qfVPDXZ7Pt', name: 'Cassidy',                  description: 'Crisp, Direct and Clear',            gender: 'Female' },
  { id: 'eR40ATw9ArzDf9h3v7t7', name: 'Addison',                  description: 'Australian Audiobook & Podcast',     gender: 'Female' },
  { id: 'g6xIsTj2HwM6VR4iXFCw', name: 'Jessica Anne Bogart',     description: 'Chatty and Friendly',                gender: 'Female' },
  { id: 'lcMyyd2HUfFzxdCaC4Ta', name: 'Lucy',                     description: 'Fresh & Casual',                     gender: 'Female' },
  { id: '6aDn1KB0hjpdcocrUkmq', name: 'Tiffany',                  description: 'Natural and Welcoming',              gender: 'Female' },
  { id: 'Sq93GQT4X1lKDXsQcixO', name: 'Felix',                    description: 'Warm, Positive & Contemporary RP',   gender: 'Male'   },
  { id: '9yzdeviXkFddZ4Oz8Mok', name: 'Lutz',                     description: 'Chuckling, Giggly and Cheerful',     gender: 'Male'   },
  { id: 'pPdl9cQBQq4p6mRkZy2Z', name: 'Emma',                     description: 'Adorable and Upbeat',                gender: 'Female' },
  { id: 'zYcjlYFOd3taleS0gkk3', name: 'Edward',                   description: 'Loud, Confident and Cocky',          gender: 'Male'   },
  { id: 'nzeAacJi50IvxcyDnMXa', name: 'Marshal',                  description: 'Friendly, Funny Professor',          gender: 'Male'   },
  { id: 'ruirxsoakN0GWmGNIo04', name: 'John Morgan',              description: 'Gritty, Rugged Cowboy',              gender: 'Male'   },
  { id: 'TC0Zp7WVFzhA8zpTlRqV', name: 'Aria',                     description: 'Sultry Villain',                     gender: 'Female' },
  { id: '8JVbfL6oEdmuxKn5DK2C', name: 'Johnny Kid',               description: 'Serious and Calm Narrator',          gender: 'Male'   },
  { id: 'wJqPPQ618aTW29mptyoc', name: 'Ana Rita',                  description: 'Smooth, Expressive and Bright',      gender: 'Female' },
  { id: 'EiNlNiXeDU1pqqOPrYMO', name: 'John Doe',                 description: 'Deep',                               gender: 'Male'   },
  { id: '6F5Zhi321D3Oq7v1oNT4', name: 'Hank',                     description: 'Deep and Engaging Narrator',         gender: 'Male'   },
  { id: 'LG95yZDEHg6fCZdQjLqj', name: 'Phil',                     description: 'Explosive, Passionate Announcer',    gender: 'Male'   },
  { id: 'CeNX9CMwmxDxUF5Q2Inm', name: 'Johnny Dynamite',         description: 'Vintage Radio DJ',                   gender: 'Male'   },
  { id: 'aD6riP1btT197c6dACmy', name: 'Rachel M',                 description: 'Pro British Radio Presenter',        gender: 'Female' },
  { id: 'mtrellq69YZsNwzUSyXh', name: 'Rex Thunder',              description: 'Deep N Tough',                       gender: 'Male'   },
  { id: 'dHd5gvgSOzSfduK4CvEg', name: 'Ed',                       description: 'Late Night Announcer',               gender: 'Male'   },
  { id: 'eVItLK1UvXctxuaRV2Oq', name: 'Jean',                     description: 'Alluring and Playful Femme Fatale',  gender: 'Female' },
  { id: 'Tsns2HvNFKfGiNjllgqo', name: 'Sven',                     description: 'Emotional and Nice',                 gender: 'Male'   },
  { id: '1U02n4nD6AdIZ9CjF053', name: 'Viraj (Gentle)',           description: 'Smooth and Gentle',                  gender: 'Male'   },
  { id: 'AeRdCCKzvd23BpJoofzx', name: 'Nathaniel',                description: 'Engaging, British and Calm',         gender: 'Male'   },
  { id: 'LruHrtVF6PSyGItzMNHS', name: 'Benjamin',                 description: 'Deep, Warm, Calming',                gender: 'Male'   },
  { id: '1wGbFxmAM3Fgw63G1zZJ', name: 'Allison',                  description: 'Calm, Soothing and Meditative',      gender: 'Female' },
  { id: 'hqfrgApggtO1785R4Fsn', name: 'Theodore',                 description: 'Serene and Grounded',                gender: 'Male'   },
  { id: 'MJ0RnG71ty4LH3dvNfSd', name: 'Leon',                     description: 'Soothing and Grounded',              gender: 'Male'   },
].map(v => ({
  ...v,
  accent: v.gender === 'Female' ? 'Female' : 'Male',
  previewUrl: `${KIE_PREVIEW_BASE}/${v.id}.mp3`,
}))

export async function getVoices() {
  return KIE_VOICES
}

  
  export const LANGUAGES = [
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Spanish' },
    { code: 'fr', name: 'French' },
    { code: 'de', name: 'German' },
    { code: 'it', name: 'Italian' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'nl', name: 'Dutch' },
    { code: 'pl', name: 'Polish' },
    { code: 'sv', name: 'Swedish' },
    { code: 'no', name: 'Norwegian' },
    { code: 'da', name: 'Danish' },
    { code: 'fi', name: 'Finnish' },
    { code: 'ru', name: 'Russian' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'ar', name: 'Arabic' },
    { code: 'tr', name: 'Turkish' },
    { code: 'hi', name: 'Hindi' },
    { code: 'zh', name: 'Chinese' },
    { code: 'ja', name: 'Japanese' },
    { code: 'ko', name: 'Korean' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ms', name: 'Malay' },
    { code: 'fil', name: 'Filipino' },
    { code: 'vi', name: 'Vietnamese' },
    { code: 'ro', name: 'Romanian' },
    { code: 'cs', name: 'Czech' },
    { code: 'sk', name: 'Slovak' },
    { code: 'bg', name: 'Bulgarian' },
    { code: 'hr', name: 'Croatian' },
    { code: 'el', name: 'Greek' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'ta', name: 'Tamil' },
  ]
  
  export const ASPECT_RATIOS = ['9:16', '1:1', '16:9']