export const ACTORS = [
    { 
      id: 1, 
      name: 'Melissa', 
      thumbnail: '👩🏻',
      imageUrl: 'https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Melissa.png',
      category: 'Female', 
    },
    { id: 2, name: 'David', thumbnail: '👨🏽', category: 'Male' , imageUrl : "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/David.png" },

    {
    id: 3,
    name: "Alex",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Alex_Caucasian_Young_Male.png",
  },
  {
    id: 4,
    name: "Anna",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Anna_Caucasian_Young_Female.png",
  },
  {
    id: 5,
    name: "Darius",
    thumbnail: "👨🏾",
    category: "Male",
    Age: "Young",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Darius_Black_Young_Male.png",
  },
  {
    id: 6,
    name: "David",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/David_Caucasian_Young_Male.png",
  },
  {
    id: 7,
    name: "Emily",
    thumbnail: "👩🏻",
    category: "Female",
    Age: "Old",
    Race: "Asian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Emily_Asian_Old_Female.png",
  },
  {
    id: 8,
    name: "Hannah",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Hannah_Caucasian_Young_Female.png",
  },
  {
    id: 9,
    name: "Jake",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Jake_Caucasian_Young_Male.png",
  },
  {
    id: 10,
    name: "Jasmine",
    thumbnail: "👩🏾",
    category: "Female",
    Age: "Young",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Jasmine_Black_Young_Female.png",
  },
  {
    id: 11,
    name: "Jessica",
    thumbnail: "👩🏻",
    category: "Female",
    Age: "Young",
    Race: "Asian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Jessica_Asian_Young_Female.png",
  },
  {
    id: 12,
    name: "John",
    thumbnail: "👨🏾",
    category: "Male",
    Age: "Old",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/John_Black_Old_Male.png",
  },
  {
    id: 13,
    name: "John",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/John_Caucasian_Old_Male.png",
  },
  {
    id: 14,
    name: "Kayla",
    thumbnail: "👩🏾",
    category: "Female",
    Age: "Old",
    Race: "Black",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Kayla_Black_Old_Female.png",
  },
  {
    id: 15,
    name: "Linda",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Linda_Caucasian_Old_Female.png",
  },
  {
    id: 16,
    name: "Logan",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Logan_Caucasian_Young_Male.png",
  },
  {
    id: 17,
    name: "Madison",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Madison_Caucasian_Young_Female.png",
  },
  {
    id: 18,
    name: "Michael",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Michael_Caucasian_Old_Male.png",
  },
  {
    id: 19,
    name: "Natalie",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Natalie_Caucasian_Young_Female.png",
  },
  {
    id: 20,
    name: "Ryan",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Ryan_Caucasian_Young_Male.png",
  },
  {
    id: 21,
    name: "Susan",
    thumbnail: "👩🏼",
    category: "Female",
    Age: "Old",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Susan_Caucasian_Old_Female.png",
  },
  {
    id: 22,
    name: "Tyler",
    thumbnail: "👨🏼",
    category: "Male",
    Age: "Young",
    Race: "Caucasian",
    imageUrl: "https://lfhcefxmgyjzggqzsxxr.supabase.co/storage/v1/object/public/avatars/Tyler_Caucasian_Young_Male.png",
  }
  ]
  
  export const VOICES = [
    { 
      id: 'Rachel', 
      name: 'Rachel - Professional', 
      gender: 'Female', 
      accent: 'American',
      elevenLabsId: 'Rachel',  // kie.ai voice name
      previewUrl: "https://xhgyetplfalikakyxjbo.supabase.co/storage/v1/object/public/voice-previews/rachel.mp3" ,
    },
    { 
      id: 'Aria', 
      name: 'Aria - Warm', 
      gender: 'Female', 
      accent: 'American',
      elevenLabsId: 'Aria',
      previewUrl: "https://xhgyetplfalikakyxjbo.supabase.co/storage/v1/object/public/voice-previews/aria.mp3" ,

    },
    { 
      id: 'Roger', 
      name: 'Roger - Authoritative', 
      gender: 'Male', 
      accent: 'American',
      elevenLabsId: 'Roger',
      previewUrl: "https://xhgyetplfalikakyxjbo.supabase.co/storage/v1/object/public/voice-previews/roger.mp3" ,

    },
    { 
      id: 'Sarah', 
      name: 'Sarah - Friendly', 
      gender: 'Female', 
      accent: 'American',
      elevenLabsId: 'Sarah',
      previewUrl: "https://xhgyetplfalikakyxjbo.supabase.co/storage/v1/object/public/voice-previews/sarah.mp3" ,

    },
    { 
      id: 'Laura', 
      name: 'Laura - Energetic', 
      gender: 'Female', 
      accent: 'American',
      elevenLabsId: 'Laura',
      previewUrl: "https://xhgyetplfalikakyxjbo.supabase.co/storage/v1/object/public/voice-previews/laura.mp3" ,

      
    },
    { 
      id: 'Charlie', 
      name: 'Charlie - Casual', 
      gender: 'Male', 
      accent: 'American',
      elevenLabsId: 'Charlie',
      previewUrl: "https://xhgyetplfalikakyxjbo.supabase.co/storage/v1/object/public/voice-previews/charlie.mp3" ,

    },
    { 
      id: 'George', 
      name: 'George - Warm', 
      gender: 'Male', 
      accent: 'British',
      elevenLabsId: 'George',
      previewUrl: "https://xhgyetplfalikakyxjbo.supabase.co/storage/v1/object/public/voice-previews/george.mp3" ,

    },
    
  ]
  
  export const LANGUAGES = [
    { code: 'en', name: 'English' },

  ]
  
  export const ASPECT_RATIOS = ['9:16', '1:1', '16:9']